# NOTE: Generated By HttpRunner v3.1.4
# FROM: har\login1.har
from httprunner import HttpRunner, Config, Step, RunTestCase
from testcases.login826_test import TestCaseLogin826 as MubuLogin


class TestCaseLogin1(HttpRunner):
    # @pytest.mark.parametrize(
    #     "param",
    #     Parameters(
    #         {
    #             "title-node1-node2": [
    #                 ["dome1", "node11", "node22"],
    #                 ["dome2", "node33", "node44"],
    #             ],
    #         }
    #     ),
    # )
    # def test_start(self, param):
    #     super().test_start(param)

    _config = Config("login")
    _conf = _config.conf()
    _headers_get = _config.headers_get()
    _headers_post = _config.headers_post()
    _cookies = _config.cookies()

    config = _config.verify(False).variables(**_conf).variables(**{"phone": "13544871706", "password": "100100"}).variables(
            **{
                "host": "mubu.com",
                "title": "demo1221",
                "node1": "node1",
                "node2": "span2",
            })
    
    teststeps = [
        Step(RunTestCase("login_mubu").call(MubuLogin).export("userId")),
        # Step(
        #     RunRequest("/api/list/create_doc")
        #     .with_variables(**{"length": "17", "referer": "https://${host}/list"})
        #     .post("/api/list/create_doc")
        #     .with_headers(**_headers_get)
        #     .with_cookies(**_cookies)
        #     .with_data({"folderId": "0", "type": "0"})
        #     .extract()
        #     .with_jmespath("body.data.id", "fileID")
        #     .validate()
        #     .assert_equal("status_code", 200)
        #     .assert_equal("body.code", 0)
        #     .assert_equal("body.msg", None)
        # ),
        # Step(
        #     RunRequest("/doc${fileID}")
        #     .get("/doc${fileID}")
        #     .with_headers(
        #         **{
        #             "Host": "${host}",
        #             "Connection": "keep-alive",
        #             "Upgrade-Insecure-Requests": "1",
        #             "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36",
        #             "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
        #             "Sec-Fetch-Site": "same-origin",
        #             "Sec-Fetch-Mode": "navigate",
        #             "Sec-Fetch-User": "?1",
        #             "Sec-Fetch-Dest": "document",
        #             "Referer": "https://${host}/list",
        #             "Accept-Encoding": "gzip, deflate, br",
        #             "Accept-Language": "zh-CN,zh;q=0.9,zh-TW;q=0.8,en-US;q=0.7,en;q=0.6",
        #             "Cookie": **_cookies,
        #         }
        #     )
        #     .with_cookies(
        #         **{
        #             "data_unique_id": "7222cae2-b7dc-4408-9f71-807c68a3eb81",
        #             "language": "en-US",
        #             "country": "US",
        #             "reg_entrance": "https%3A%2F%2F${host}%2F",
        #             "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1596433171",
        #             "_ga": "GA1.2.1822844197.1596433171",
        #             "_gid": "GA1.2.2112073243.1596433171",
        #             "s_v_web_id": "kde36rau_LbJCnUtY_WxfM_48aF_Bea9_0F8PeXcfQ9MB",
        #             "mubu_inner": "1",
        #             "reg_prepareId": "173b3160664-173b3160418-405b-b009-127f9ee6f272",
        #             "reg_focusId": "e1ac6342-8037-405b-b009-173b3161767",
        #             "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiODQ5MTE4MiIsImV4cCI6MTU5OTAyOTQ0NSwiaWF0IjoxNTk2NDM3NDQ1fQ.MNuIiNww73fm28w6ELIvXl0CccwDVLMAjur9gs0zzsmsoJF9GHPTZ4oQ6tlsf4nTjyXXdATenU9mpSq8vZ9qow",
        #             "csrf_token": "326e418c-1b22-4251-a13c-e32f61e093cb",
        #             "SESSION": "a6a72748-510d-4a5b-8f2e-249d48f0f426",
        #             "data-unique-id": "660d4f70-d55b-11ea-8393-1d9974416b80",
        #             "SLARDAR_WEB_ID": "e134201e-e669-4b2e-b063-2d6db1ad9477",
        #             "_gat": "1",
        #             "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1596439968",
        #         }
        #     )
        #     .validate()
        #     .assert_equal("status_code", 200)
        #     .assert_equal('headers."Content-Type"', "text/html; charset=utf-8")
        # ),
        # Step(
        #     RunRequest("/v3/api/document/get")
        #     .post("https://api2.${host}/v3/api/document/get")
        #     .with_headers(
        #         **{
        #             "Host": "api2.${host}",
        #             "Connection": "keep-alive",
        #             "Content-Length": "23",
        #             "Accept": "application/json, text/plain, */*",
        #             "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiODQ5MTE4MiIsImV4cCI6MTU5OTAyOTQ0NSwiaWF0IjoxNTk2NDM3NDQ1fQ.MNuIiNww73fm28w6ELIvXl0CccwDVLMAjur9gs0zzsmsoJF9GHPTZ4oQ6tlsf4nTjyXXdATenU9mpSq8vZ9qow",
        #             "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36",
        #             "data-unique-id": "660d4f70-d55b-11ea-8393-1d9974416b80",
        #             "x-request-id": "69f7ae89-ea0a-4058-96a8-1541e9fce2a2",
        #             "Content-Type": "application/json;charset=UTF-8",
        #             "Origin": "https://${host}",
        #             "Sec-Fetch-Site": "same-site",
        #             "Sec-Fetch-Mode": "cors",
        #             "Sec-Fetch-Dest": "empty",
        #             "Referer": "https://${host}/doc${fileID}",
        #             "Accept-Encoding": "gzip, deflate, br",
        #             "Accept-Language": "zh-CN,zh;q=0.9,zh-TW;q=0.8,en-US;q=0.7,en;q=0.6",
        #         }
        #     )
        #     .with_json({"docId": "${fileID}"})
        #     .validate()
        #     .assert_equal("status_code", 200)
        #     .assert_equal('headers."Content-Type"', "application/json;charset=utf-8")
        #     .assert_equal("body.code", 0)
        #     .assert_equal("body.msg", "Success")
        # ),
        # Step(
        #     RunRequest("/v3/api/user/current_level")
        #     .post("https://api2.${host}/v3/api/user/current_level")
        #     .with_headers(
        #         **{
        #             "Host": "api2.${host}",
        #             "Connection": "keep-alive",
        #             "Content-Length": "29",
        #             "Accept": "application/json, text/plain, */*",
        #             "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiODQ5MTE4MiIsImV4cCI6MTU5OTAyOTQ0NSwiaWF0IjoxNTk2NDM3NDQ1fQ.MNuIiNww73fm28w6ELIvXl0CccwDVLMAjur9gs0zzsmsoJF9GHPTZ4oQ6tlsf4nTjyXXdATenU9mpSq8vZ9qow",
        #             "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36",
        #             "data-unique-id": "660d4f70-d55b-11ea-8393-1d9974416b80",
        #             "x-request-id": "9a11fd97-f56c-4ef8-92ac-55342de5b984",
        #             "Content-Type": "application/json;charset=UTF-8",
        #             "Origin": "https://${host}",
        #             "Sec-Fetch-Site": "same-site",
        #             "Sec-Fetch-Mode": "cors",
        #             "Sec-Fetch-Dest": "empty",
        #             "Referer": "https://${host}/doc${fileID}",
        #             "Accept-Encoding": "gzip, deflate, br",
        #             "Accept-Language": "zh-CN,zh;q=0.9,zh-TW;q=0.8,en-US;q=0.7,en;q=0.6",
        #         }
        #     )
        #     .with_json({"document_id": "${fileID}"})
        #     .validate()
        #     .assert_equal("status_code", 200)
        #     .assert_equal('headers."Content-Type"', "application/json;charset=utf-8")
        #     .assert_equal("body.code", 0)
        #     .assert_equal("body.msg", "OK")
        # ),
        # Step(
        #     RunRequest("/v3/api/user/current_user")
        #     .post("https://api2.${host}/v3/api/user/current_user")
        #     .with_headers(
        #         **{
        #             "Host": "api2.${host}",
        #             "Connection": "keep-alive",
        #             "Content-Length": "0",
        #             "Accept": "application/json, text/plain, */*",
        #             "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiODQ5MTE4MiIsImV4cCI6MTU5OTAyOTQ0NSwiaWF0IjoxNTk2NDM3NDQ1fQ.MNuIiNww73fm28w6ELIvXl0CccwDVLMAjur9gs0zzsmsoJF9GHPTZ4oQ6tlsf4nTjyXXdATenU9mpSq8vZ9qow",
        #             "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36",
        #             "data-unique-id": "660d4f70-d55b-11ea-8393-1d9974416b80",
        #             "x-request-id": "fbaa04e1-6d26-4e8c-bc49-837faecb0834",
        #             "Origin": "https://${host}",
        #             "Sec-Fetch-Site": "same-site",
        #             "Sec-Fetch-Mode": "cors",
        #             "Sec-Fetch-Dest": "empty",
        #             "Referer": "https://${host}/doc${fileID}",
        #             "Accept-Encoding": "gzip, deflate, br",
        #             "Accept-Language": "zh-CN,zh;q=0.9,zh-TW;q=0.8,en-US;q=0.7,en;q=0.6",
        #         }
        #     )
        #     .with_data("")
        #     .validate()
        #     .assert_equal("status_code", 200)
        #     .assert_equal('headers."Content-Type"', "application/json;charset=utf-8")
        #     .assert_equal("body.code", 0)
        #     .assert_equal("body.msg", "success")
        # ),
        # Step(
        #     RunRequest("/v3/api/user/get_user_params")
        #     .post("https://api2.${host}/v3/api/user/get_user_params")
        #     .with_headers(
        #         **{
        #             "Host": "api2.${host}",
        #             "Connection": "keep-alive",
        #             "Content-Length": "0",
        #             "Accept": "application/json, text/plain, */*",
        #             "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiODQ5MTE4MiIsImV4cCI6MTU5OTAyOTQ0NSwiaWF0IjoxNTk2NDM3NDQ1fQ.MNuIiNww73fm28w6ELIvXl0CccwDVLMAjur9gs0zzsmsoJF9GHPTZ4oQ6tlsf4nTjyXXdATenU9mpSq8vZ9qow",
        #             "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36",
        #             "data-unique-id": "660d4f70-d55b-11ea-8393-1d9974416b80",
        #             "x-request-id": "fc09b5d9-4538-43e5-a3ea-5e5d7dc12de4",
        #             "Origin": "https://${host}",
        #             "Sec-Fetch-Site": "same-site",
        #             "Sec-Fetch-Mode": "cors",
        #             "Sec-Fetch-Dest": "empty",
        #             "Referer": "https://${host}/doc${fileID}",
        #             "Accept-Encoding": "gzip, deflate, br",
        #             "Accept-Language": "zh-CN,zh;q=0.9,zh-TW;q=0.8,en-US;q=0.7,en;q=0.6",
        #         }
        #     )
        #     .with_data("")
        #     .validate()
        #     .assert_equal("status_code", 200)
        #     .assert_equal('headers."Content-Type"', "application/json;charset=utf-8")
        #     .assert_equal("body.code", 0)
        #     .assert_equal("body.msg", "success")
        # ),
        # Step(
        #     RunRequest("/v3/api/user/get_invite_count")
        #     .get("https://api2.${host}/v3/api/user/get_invite_count")
        #     .with_headers(
        #         **{
        #             "Host": "api2.${host}",
        #             "Connection": "keep-alive",
        #             "Accept": "application/json, text/plain, */*",
        #             "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiODQ5MTE4MiIsImV4cCI6MTU5OTAyOTQ0NSwiaWF0IjoxNTk2NDM3NDQ1fQ.MNuIiNww73fm28w6ELIvXl0CccwDVLMAjur9gs0zzsmsoJF9GHPTZ4oQ6tlsf4nTjyXXdATenU9mpSq8vZ9qow",
        #             "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36",
        #             "data-unique-id": "660d4f70-d55b-11ea-8393-1d9974416b80",
        #             "x-request-id": "071eb6e5-99e8-4459-b7ee-3e45dd6f87d9",
        #             "Origin": "https://${host}",
        #             "Sec-Fetch-Site": "same-site",
        #             "Sec-Fetch-Mode": "cors",
        #             "Sec-Fetch-Dest": "empty",
        #             "Referer": "https://${host}/doc${fileID}",
        #             "Accept-Encoding": "gzip, deflate, br",
        #             "Accept-Language": "zh-CN,zh;q=0.9,zh-TW;q=0.8,en-US;q=0.7,en;q=0.6",
        #         }
        #     )
        #     .validate()
        #     .assert_equal("status_code", 200)
        #     .assert_equal('headers."Content-Type"', "application/json;charset=utf-8")
        #     .assert_equal("body.code", 0)
        # ),
        # Step(
        #     RunRequest("/v3/api/colla/register")
        #     .get("https://api2.${host}/v3/api/colla/register")
        #     .with_headers(
        #         **{
        #             "Host": "api2.${host}",
        #             "Connection": "keep-alive",
        #             "Accept": "application/json, text/plain, */*",
        #             "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiODQ5MTE4MiIsImV4cCI6MTU5OTAyOTQ0NSwiaWF0IjoxNTk2NDM3NDQ1fQ.MNuIiNww73fm28w6ELIvXl0CccwDVLMAjur9gs0zzsmsoJF9GHPTZ4oQ6tlsf4nTjyXXdATenU9mpSq8vZ9qow",
        #             "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36",
        #             "data-unique-id": "660d4f70-d55b-11ea-8393-1d9974416b80",
        #             "x-request-id": "23969a64-f2bf-4639-be20-eb1aaee2e5b6",
        #             "Origin": "https://${host}",
        #             "Sec-Fetch-Site": "same-site",
        #             "Sec-Fetch-Mode": "cors",
        #             "Sec-Fetch-Dest": "empty",
        #             "Referer": "https://${host}/doc${fileID}",
        #             "Accept-Encoding": "gzip, deflate, br",
        #             "Accept-Language": "zh-CN,zh;q=0.9,zh-TW;q=0.8,en-US;q=0.7,en;q=0.6",
        #         }
        #     )
        #     .validate()
        #     .assert_equal("status_code", 200)
        #     .assert_equal('headers."Content-Type"', "application/json;charset=utf-8")
        #     .assert_equal("body.code", 0)
        #     .assert_equal("body.msg", "Success")
        # ),
        # Step(
        #     RunRequest("/v3/api/colla/members")
        #     .options("https://api2.${host}/v3/api/colla/members")
        #     .with_params(**{"memberId": "6093059803590483", "documentId": "${fileID}"})
        #     .with_headers(
        #         **{
        #             "Host": "api2.${host}",
        #             "Connection": "keep-alive",
        #             "Accept": "*/*",
        #             "Access-Control-Request-Method": "GET",
        #             "Access-Control-Request-Headers": "data-unique-id,jwt-token,request-id,x-request-id",
        #             "Origin": "https://${host}",
        #             "Sec-Fetch-Mode": "cors",
        #             "Sec-Fetch-Site": "same-site",
        #             "Sec-Fetch-Dest": "empty",
        #             "Referer": "https://${host}/doc${fileID}",
        #             "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36",
        #             "Accept-Encoding": "gzip, deflate, br",
        #             "Accept-Language": "zh-CN,zh;q=0.9,zh-TW;q=0.8,en-US;q=0.7,en;q=0.6",
        #         }
        #     )
        #     .validate()
        #     .assert_equal("status_code", 200)
        #     .assert_equal('headers."Content-Type"', "application/octet-stream")
        # ),
        # Step(
        #     RunRequest("/v3/api/colla/members")
        #     .get("https://api2.${host}/v3/api/colla/members")
        #     .with_params(**{"memberId": "6093059803590483", "documentId": "${fileID}"})
        #     .with_headers(
        #         **{
        #             "Host": "api2.${host}",
        #             "Connection": "keep-alive",
        #             "Accept": "application/json, text/plain, */*",
        #             "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiODQ5MTE4MiIsImV4cCI6MTU5OTAyOTQ0NSwiaWF0IjoxNTk2NDM3NDQ1fQ.MNuIiNww73fm28w6ELIvXl0CccwDVLMAjur9gs0zzsmsoJF9GHPTZ4oQ6tlsf4nTjyXXdATenU9mpSq8vZ9qow",
        #             "Request-Id": "members:6093059803590483:1596439987183",
        #             "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36",
        #             "data-unique-id": "660d4f70-d55b-11ea-8393-1d9974416b80",
        #             "x-request-id": "89c4896d-9746-4154-a946-088979e638ab",
        #             "Origin": "https://${host}",
        #             "Sec-Fetch-Site": "same-site",
        #             "Sec-Fetch-Mode": "cors",
        #             "Sec-Fetch-Dest": "empty",
        #             "Referer": "https://${host}/doc${fileID}",
        #             "Accept-Encoding": "gzip, deflate, br",
        #             "Accept-Language": "zh-CN,zh;q=0.9,zh-TW;q=0.8,en-US;q=0.7,en;q=0.6",
        #         }
        #     )
        #     .validate()
        #     .assert_equal("status_code", 200)
        #     .assert_equal('headers."Content-Type"', "application/json;charset=utf-8")
        #     .assert_equal("body.code", 0)
        #     .assert_equal("body.msg", "success")
        # ),
        # Step(
        #     RunRequest("/v3/api/colla/message")
        #     .post("https://api2.${host}/v3/api/colla/message")
        #     .with_headers(
        #         **{
        #             "Host": "api2.${host}",
        #             "Connection": "keep-alive",
        #             "Content-Length": "407",
        #             "Member-Id": "6093059803590483",
        #             "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36",
        #             "data-unique-id": "660d4f70-d55b-11ea-8393-1d9974416b80",
        #             "Content-Type": "application/json;charset=UTF-8",
        #             "Accept": "application/json, text/plain, */*",
        #             "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiODQ5MTE4MiIsImV4cCI6MTU5OTAyOTQ0NSwiaWF0IjoxNTk2NDM3NDQ1fQ.MNuIiNww73fm28w6ELIvXl0CccwDVLMAjur9gs0zzsmsoJF9GHPTZ4oQ6tlsf4nTjyXXdATenU9mpSq8vZ9qow",
        #             "Request-Id": "MESSAGE:${userId}:6093059803590483:3",
        #             "x-request-id": "9b511855-bf01-4373-a8e2-7a5122c5427f",
        #             "Origin": "https://${host}",
        #             "Sec-Fetch-Site": "same-site",
        #             "Sec-Fetch-Mode": "cors",
        #             "Sec-Fetch-Dest": "empty",
        #             "Referer": "https://${host}/doc${fileID}",
        #             "Accept-Encoding": "gzip, deflate, br",
        #             "Accept-Language": "zh-CN,zh;q=0.9,zh-TW;q=0.8,en-US;q=0.7,en;q=0.6",
        #         }
        #     )
        #     .with_json(
        #         {
        #             "engineType": "MUBU",
        #             "messageType": "BROADCAST",
        #             "reqId": 3,
        #             "requestId": "MESSAGE:${userId}:6093059803590483:3",
        #             "token": "${fileID}",
        #             "data": {
        #                 "message": {
        #                     "type": "CHANGE",
        #                     "documentId": "${fileID}",
        #                     "version": 0,
        #                     "content": [
        #                         {"name": "nameChanged", "title": "d", "original": ""},
        #                         {"name": "nameChanged", "title": "de", "original": "d"},
        #                     ],
        #                 }
        #             },
        #             "context": {
        #                 "os": "Windows",
        #                 "osVersion": "NT 10.0",
        #                 "appVersion": "1.0.0.289",
        #                 "platform": "web",
        #             },
        #         }
        #     )
        #     .validate()
        #     .assert_equal("status_code", 200)
        #     .assert_equal('headers."Content-Type"', "application/json;charset=utf-8")
        #     .assert_equal("body.code", 0)
        #     .assert_equal("body.msg", "success")
        # ),
        # Step(
        #     RunRequest("/v3/api/colla/message")
        #     .post("https://api2.${host}/v3/api/colla/message")
        #     .with_headers(
        #         **{
        #             "Host": "api2.${host}",
        #             "Connection": "keep-alive",
        #             "Content-Length": "360",
        #             "Member-Id": "6093059803590483",
        #             "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36",
        #             "data-unique-id": "660d4f70-d55b-11ea-8393-1d9974416b80",
        #             "Content-Type": "application/json;charset=UTF-8",
        #             "Accept": "application/json, text/plain, */*",
        #             "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiODQ5MTE4MiIsImV4cCI6MTU5OTAyOTQ0NSwiaWF0IjoxNTk2NDM3NDQ1fQ.MNuIiNww73fm28w6ELIvXl0CccwDVLMAjur9gs0zzsmsoJF9GHPTZ4oQ6tlsf4nTjyXXdATenU9mpSq8vZ9qow",
        #             "Request-Id": "MESSAGE:${userId}:6093059803590483:5",
        #             "x-request-id": "14107e12-a4de-4c4b-8a69-405ec81ded96",
        #             "Origin": "https://${host}",
        #             "Sec-Fetch-Site": "same-site",
        #             "Sec-Fetch-Mode": "cors",
        #             "Sec-Fetch-Dest": "empty",
        #             "Referer": "https://${host}/doc${fileID}",
        #             "Accept-Encoding": "gzip, deflate, br",
        #             "Accept-Language": "zh-CN,zh;q=0.9,zh-TW;q=0.8,en-US;q=0.7,en;q=0.6",
        #         }
        #     )
        #     .with_json(
        #         {
        #             "engineType": "MUBU",
        #             "messageType": "BROADCAST",
        #             "reqId": 5,
        #             "requestId": "MESSAGE:${userId}:6093059803590483:5",
        #             "token": "${fileID}",
        #             "data": {
        #                 "message": {
        #                     "type": "CHANGE",
        #                     "documentId": "${fileID}",
        #                     "version": 1,
        #                     "content": [
        #                         {
        #                             "name": "nameChanged",
        #                             "title": "dem",
        #                             "original": "de",
        #                         }
        #                     ],
        #                 }
        #             },
        #             "context": {
        #                 "os": "Windows",
        #                 "osVersion": "NT 10.0",
        #                 "appVersion": "1.0.0.289",
        #                 "platform": "web",
        #             },
        #         }
        #     )
        #     .validate()
        #     .assert_equal("status_code", 200)
        #     .assert_equal('headers."Content-Type"', "application/json;charset=utf-8")
        #     .assert_equal("body.code", 0)
        #     .assert_equal("body.msg", "success")
        # ),
        # Step(
        #     RunRequest("/v3/api/colla/message")
        #     .post("https://api2.${host}/v3/api/colla/message")
        #     .with_headers(
        #         **{
        #             "Host": "api2.${host}",
        #             "Connection": "keep-alive",
        #             "Content-Length": "362",
        #             "Member-Id": "6093059803590483",
        #             "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36",
        #             "data-unique-id": "660d4f70-d55b-11ea-8393-1d9974416b80",
        #             "Content-Type": "application/json;charset=UTF-8",
        #             "Accept": "application/json, text/plain, */*",
        #             "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiODQ5MTE4MiIsImV4cCI6MTU5OTAyOTQ0NSwiaWF0IjoxNTk2NDM3NDQ1fQ.MNuIiNww73fm28w6ELIvXl0CccwDVLMAjur9gs0zzsmsoJF9GHPTZ4oQ6tlsf4nTjyXXdATenU9mpSq8vZ9qow",
        #             "Request-Id": "MESSAGE:${userId}:6093059803590483:6",
        #             "x-request-id": "327022e5-77f7-408e-a919-0da5fbb517c9",
        #             "Origin": "https://${host}",
        #             "Sec-Fetch-Site": "same-site",
        #             "Sec-Fetch-Mode": "cors",
        #             "Sec-Fetch-Dest": "empty",
        #             "Referer": "https://${host}/doc${fileID}",
        #             "Accept-Encoding": "gzip, deflate, br",
        #             "Accept-Language": "zh-CN,zh;q=0.9,zh-TW;q=0.8,en-US;q=0.7,en;q=0.6",
        #         }
        #     )
        #     .with_json(
        #         {
        #             "engineType": "MUBU",
        #             "messageType": "BROADCAST",
        #             "reqId": 6,
        #             "requestId": "MESSAGE:${userId}:6093059803590483:6",
        #             "token": "${fileID}",
        #             "data": {
        #                 "message": {
        #                     "type": "CHANGE",
        #                     "documentId": "${fileID}",
        #                     "version": 2,
        #                     "content": [
        #                         {
        #                             "name": "nameChanged",
        #                             "title": "${title}",
        #                             "original": "",
        #                         }
        #                     ],
        #                 }
        #             },
        #             "context": {
        #                 "os": "Windows",
        #                 "osVersion": "NT 10.0",
        #                 "appVersion": "1.0.0.289",
        #                 "platform": "web",
        #             },
        #         }
        #     )
        #     .validate()
        #     .assert_equal("status_code", 200)
        #     .assert_equal('headers."Content-Type"', "application/json;charset=utf-8")
        #     .assert_equal("body.code", 0)
        #     .assert_equal("body.msg", "success")
        # ),
        # Step(
        #     RunRequest("/v3/api/colla/message")
        #     .post("https://api2.${host}/v3/api/colla/message")
        #     .with_headers(
        #         **{
        #             "Host": "api2.${host}",
        #             "Connection": "keep-alive",
        #             "Content-Length": "722",
        #             "Member-Id": "6093059803590483",
        #             "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36",
        #             "data-unique-id": "660d4f70-d55b-11ea-8393-1d9974416b80",
        #             "Content-Type": "application/json;charset=UTF-8",
        #             "Accept": "application/json, text/plain, */*",
        #             "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiODQ5MTE4MiIsImV4cCI6MTU5OTAyOTQ0NSwiaWF0IjoxNTk2NDM3NDQ1fQ.MNuIiNww73fm28w6ELIvXl0CccwDVLMAjur9gs0zzsmsoJF9GHPTZ4oQ6tlsf4nTjyXXdATenU9mpSq8vZ9qow",
        #             "Request-Id": "MESSAGE:${userId}:6093059803590483:8",
        #             "x-request-id": "5ef9ce35-4ed2-410c-895e-0e0e1eac0547",
        #             "Origin": "https://${host}",
        #             "Sec-Fetch-Site": "same-site",
        #             "Sec-Fetch-Mode": "cors",
        #             "Sec-Fetch-Dest": "empty",
        #             "Referer": "https://${host}/doc${fileID}",
        #             "Accept-Encoding": "gzip, deflate, br",
        #             "Accept-Language": "zh-CN,zh;q=0.9,zh-TW;q=0.8,en-US;q=0.7,en;q=0.6",
        #         }
        #     )
        #     .with_json(
        #         {
        #             "engineType": "MUBU",
        #             "messageType": "BROADCAST",
        #             "reqId": 8,
        #             "requestId": "MESSAGE:${userId}:6093059803590483:8",
        #             "token": "${fileID}",
        #             "data": {
        #                 "message": {
        #                     "type": "CHANGE",
        #                     "documentId": "${fileID}",
        #                     "version": 3,
        #                     "content": [
        #                         {
        #                             "name": "create",
        #                             "created": [
        #                                 {
        #                                     "index": 0,
        #                                     "parentId": None,
        #                                     "node": {
        #                                         "id": "9801817781ccccf6072c3a3267598c8c",
        #                                         "text": "",
        #                                         "modified": 1596439991924,
        #                                         "children": [],
        #                                     },
        #                                     "path": ["nodes", 0],
        #                                 }
        #                             ],
        #                         },
        #                         {
        #                             "name": "update",
        #                             "updated": [
        #                                 {
        #                                     "updated": {
        #                                         "id": "9801817781ccccf6072c3a3267598c8c",
        #                                         "text": "<span>$node1</span>",
        #                                         "modified": 1596439992132,
        #                                     },
        #                                     "original": {
        #                                         "id": "9801817781ccccf6072c3a3267598c8c",
        #                                         "text": "",
        #                                         "modified": 1596439991924,
        #                                     },
        #                                     "path": ["nodes", 0],
        #                                 }
        #                             ],
        #                         },
        #                     ],
        #                 }
        #             },
        #             "context": {
        #                 "os": "Windows",
        #                 "osVersion": "NT 10.0",
        #                 "appVersion": "1.0.0.289",
        #                 "platform": "web",
        #             },
        #         }
        #     )
        #     .validate()
        #     .assert_equal("status_code", 200)
        #     .assert_equal('headers."Content-Type"', "application/json;charset=utf-8")
        #     .assert_equal("body.code", 0)
        #     .assert_equal("body.msg", "success")
        # ),
        # Step(
        #     RunRequest("/v3/api/colla/message")
        #     .post("https://api2.${host}/v3/api/colla/message")
        #     .with_headers(
        #         **{
        #             "Host": "api2.${host}",
        #             "Connection": "keep-alive",
        #             "Content-Length": "484",
        #             "Member-Id": "6093059803590483",
        #             "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36",
        #             "data-unique-id": "660d4f70-d55b-11ea-8393-1d9974416b80",
        #             "Content-Type": "application/json;charset=UTF-8",
        #             "Accept": "application/json, text/plain, */*",
        #             "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiODQ5MTE4MiIsImV4cCI6MTU5OTAyOTQ0NSwiaWF0IjoxNTk2NDM3NDQ1fQ.MNuIiNww73fm28w6ELIvXl0CccwDVLMAjur9gs0zzsmsoJF9GHPTZ4oQ6tlsf4nTjyXXdATenU9mpSq8vZ9qow",
        #             "Request-Id": "MESSAGE:${userId}:6093059803590483:10",
        #             "x-request-id": "b7f639a7-46ea-4e7d-8671-de1aaf8464c7",
        #             "Origin": "https://${host}",
        #             "Sec-Fetch-Site": "same-site",
        #             "Sec-Fetch-Mode": "cors",
        #             "Sec-Fetch-Dest": "empty",
        #             "Referer": "https://${host}/doc${fileID}",
        #             "Accept-Encoding": "gzip, deflate, br",
        #             "Accept-Language": "zh-CN,zh;q=0.9,zh-TW;q=0.8,en-US;q=0.7,en;q=0.6",
        #         }
        #     )
        #     .with_json(
        #         {
        #             "engineType": "MUBU",
        #             "messageType": "BROADCAST",
        #             "reqId": 10,
        #             "requestId": "MESSAGE:${userId}:6093059803590483:10",
        #             "token": "${fileID}",
        #             "data": {
        #                 "message": {
        #                     "type": "CHANGE",
        #                     "documentId": "${fileID}",
        #                     "version": 4,
        #                     "content": [
        #                         {
        #                             "name": "create",
        #                             "created": [
        #                                 {
        #                                     "index": 1,
        #                                     "parentId": None,
        #                                     "node": {
        #                                         "id": "52a236dc1b62eecc79f6bb60deb7def2",
        #                                         "text": "",
        #                                         "modified": 1596439992913,
        #                                         "children": [],
        #                                     },
        #                                     "path": ["nodes", 1],
        #                                 }
        #                             ],
        #                         }
        #                     ],
        #                 }
        #             },
        #             "context": {
        #                 "os": "Windows",
        #                 "osVersion": "NT 10.0",
        #                 "appVersion": "1.0.0.289",
        #                 "platform": "web",
        #             },
        #         }
        #     )
        #     .validate()
        #     .assert_equal("status_code", 200)
        #     .assert_equal('headers."Content-Type"', "application/json;charset=utf-8")
        #     .assert_equal("body.code", 0)
        #     .assert_equal("body.msg", "success")
        # ),
        # Step(
        #     RunRequest("/v3/api/colla/message")
        #     .post("https://api2.${host}/v3/api/colla/message")
        #     .with_headers(
        #         **{
        #             "Host": "api2.${host}",
        #             "Connection": "keep-alive",
        #             "Content-Length": "549",
        #             "Member-Id": "6093059803590483",
        #             "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36",
        #             "data-unique-id": "660d4f70-d55b-11ea-8393-1d9974416b80",
        #             "Content-Type": "application/json;charset=UTF-8",
        #             "Accept": "application/json, text/plain, */*",
        #             "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiODQ5MTE4MiIsImV4cCI6MTU5OTAyOTQ0NSwiaWF0IjoxNTk2NDM3NDQ1fQ.MNuIiNww73fm28w6ELIvXl0CccwDVLMAjur9gs0zzsmsoJF9GHPTZ4oQ6tlsf4nTjyXXdATenU9mpSq8vZ9qow",
        #             "Request-Id": "MESSAGE:${userId}:6093059803590483:11",
        #             "x-request-id": "479e17fe-a7b7-48f6-ada8-c60405a70f66",
        #             "Origin": "https://${host}",
        #             "Sec-Fetch-Site": "same-site",
        #             "Sec-Fetch-Mode": "cors",
        #             "Sec-Fetch-Dest": "empty",
        #             "Referer": "https://${host}/doc${fileID}",
        #             "Accept-Encoding": "gzip, deflate, br",
        #             "Accept-Language": "zh-CN,zh;q=0.9,zh-TW;q=0.8,en-US;q=0.7,en;q=0.6",
        #         }
        #     )
        #     .with_json(
        #         {
        #             "engineType": "MUBU",
        #             "messageType": "BROADCAST",
        #             "reqId": 11,
        #             "requestId": "MESSAGE:${userId}:6093059803590483:11",
        #             "token": "${fileID}",
        #             "data": {
        #                 "message": {
        #                     "type": "CHANGE",
        #                     "documentId": "${fileID}",
        #                     "version": 5,
        #                     "content": [
        #                         {
        #                             "name": "update",
        #                             "updated": [
        #                                 {
        #                                     "updated": {
        #                                         "id": "52a236dc1b62eecc79f6bb60deb7def2",
        #                                         "text": "<span>$node2</span>",
        #                                         "modified": 1596439993435,
        #                                     },
        #                                     "original": {
        #                                         "id": "52a236dc1b62eecc79f6bb60deb7def2",
        #                                         "text": "",
        #                                         "modified": 1596439992913,
        #                                     },
        #                                     "path": ["nodes", 1],
        #                                 }
        #                             ],
        #                         }
        #                     ],
        #                 }
        #             },
        #             "context": {
        #                 "os": "Windows",
        #                 "osVersion": "NT 10.0",
        #                 "appVersion": "1.0.0.289",
        #                 "platform": "web",
        #             },
        #         }
        #     )
        #     .validate()
        #     .assert_equal("status_code", 200)
        #     .assert_equal('headers."Content-Type"', "application/json;charset=utf-8")
        #     .assert_equal("body.code", 0)
        #     .assert_equal("body.msg", "success")
        # ),
    ]


if __name__ == "__main__":
    TestCaseLogin1().test_start()
