# NOTE: Generated By HttpRunner v3.1.4
# FROM: har\login.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseLogin(HttpRunner):
    config = (
        Config("login_mubu")
        .verify(False)
        .variables(
            **{
            "host": "${url()}",
            "phone": "${conf(phone)}",
            "password": "${conf(password)}"
            })
        .base_url("https://${host}")
    )

    teststeps = [
        Step(
            RunRequest("/")
            .get("/")
            .with_headers(
                **{
                    "Host": "${host}",
                    "Connection": "keep-alive",
                    "Cache-Control": "max-age=0",
                    "Upgrade-Insecure-Requests": "1",
                    "User-Agent": "HttpRunner/${get_httprunner_version()}",
                    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "Sec-Fetch-Site": "same-origin",
                    "Sec-Fetch-Mode": "navigate",
                    "Sec-Fetch-User": "?1",
                    "Sec-Fetch-Dest": "document",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,zh-TW;q=0.8,en-US;q=0.7,en;q=0.6",
                    "Cookie": "data_unique_id=7222cae2-b7dc-4408-9f71-807c68a3eb81; language=en-US; country=US; reg_entrance=https%3A%2F%2F${host}%2F; Hm_lvt_4426cbb0486a79ea049b4ad52d81b504=1596433171; _ga=GA1.2.1822844197.1596433171; _gid=GA1.2.2112073243.1596433171; s_v_web_id=kde36rau_LbJCnUtY_WxfM_48aF_Bea9_0F8PeXcfQ9MB; mubu_inner=1; reg_prepareId=173b2d81b84-173b2d81975-4b0b-bef0-92f6c2c1331f; reg_focusId=07a9fea0-9e75-4b0b-bef0-173b2d827d1; csrf_token=a7d74323-93cd-42c0-925b-db9e8156ff96; SESSION=d94cb122-9971-41b6-94c0-73367f7828d1; data-unique-id=9221b340-d555-11ea-8191-09cb402f42fc; _gat=1; Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504=1596437409; SLARDAR_WEB_ID=c0b3bb04-664c-49f9-8780-1298cd42a0e7",
                }
            )
            .with_cookies(
                **{
                    "data_unique_id": "7222cae2-b7dc-4408-9f71-807c68a3eb81",
                    "language": "en-US",
                    "country": "US",
                    "reg_entrance": "https%3A%2F%2F${host}%2F",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1596433171",
                    "_ga": "GA1.2.1822844197.1596433171",
                    "_gid": "GA1.2.2112073243.1596433171",
                    "s_v_web_id": "kde36rau_LbJCnUtY_WxfM_48aF_Bea9_0F8PeXcfQ9MB",
                    "mubu_inner": "1",
                    "reg_prepareId": "173b2d81b84-173b2d81975-4b0b-bef0-92f6c2c1331f",
                    "reg_focusId": "07a9fea0-9e75-4b0b-bef0-173b2d827d1",
                    "csrf_token": "a7d74323-93cd-42c0-925b-db9e8156ff96",
                    "SESSION": "d94cb122-9971-41b6-94c0-73367f7828d1",
                    "data-unique-id": "9221b340-d555-11ea-8191-09cb402f42fc",
                    "_gat": "1",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1596437409",
                    "SLARDAR_WEB_ID": "c0b3bb04-664c-49f9-8780-1298cd42a0e7",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "text/html;charset=UTF-8")
        ),
        Step(
            RunRequest("/login")
            .get("/login")
            .with_headers(
                **{
                    "Host": "${host}",
                    "Connection": "keep-alive",
                    "Upgrade-Insecure-Requests": "1",
                    "User-Agent": "HttpRunner/${get_httprunner_version()}",
                    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "Sec-Fetch-Site": "same-origin",
                    "Sec-Fetch-Mode": "navigate",
                    "Sec-Fetch-User": "?1",
                    "Sec-Fetch-Dest": "document",
                    "Referer": "https://${host}/",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,zh-TW;q=0.8,en-US;q=0.7,en;q=0.6",
                    "Cookie": "data_unique_id=7222cae2-b7dc-4408-9f71-807c68a3eb81; language=en-US; country=US; reg_entrance=https%3A%2F%2F${host}%2F; Hm_lvt_4426cbb0486a79ea049b4ad52d81b504=1596433171; _ga=GA1.2.1822844197.1596433171; _gid=GA1.2.2112073243.1596433171; s_v_web_id=kde36rau_LbJCnUtY_WxfM_48aF_Bea9_0F8PeXcfQ9MB; mubu_inner=1; reg_prepareId=173b2d81b84-173b2d81975-4b0b-bef0-92f6c2c1331f; reg_focusId=07a9fea0-9e75-4b0b-bef0-173b2d827d1; csrf_token=a7d74323-93cd-42c0-925b-db9e8156ff96; SESSION=d94cb122-9971-41b6-94c0-73367f7828d1; data-unique-id=9221b340-d555-11ea-8191-09cb402f42fc; _gat=1; SLARDAR_WEB_ID=2e99704f-2f35-4058-b733-e1c72673463b; Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504=1596437424",
                }
            )
            .with_cookies(
                **{
                    "data_unique_id": "7222cae2-b7dc-4408-9f71-807c68a3eb81",
                    "language": "en-US",
                    "country": "US",
                    "reg_entrance": "https%3A%2F%2F${host}%2F",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1596433171",
                    "_ga": "GA1.2.1822844197.1596433171",
                    "_gid": "GA1.2.2112073243.1596433171",
                    "s_v_web_id": "kde36rau_LbJCnUtY_WxfM_48aF_Bea9_0F8PeXcfQ9MB",
                    "mubu_inner": "1",
                    "reg_prepareId": "173b2d81b84-173b2d81975-4b0b-bef0-92f6c2c1331f",
                    "reg_focusId": "07a9fea0-9e75-4b0b-bef0-173b2d827d1",
                    "csrf_token": "a7d74323-93cd-42c0-925b-db9e8156ff96",
                    "SESSION": "d94cb122-9971-41b6-94c0-73367f7828d1",
                    "data-unique-id": "9221b340-d555-11ea-8191-09cb402f42fc",
                    "_gat": "1",
                    "SLARDAR_WEB_ID": "2e99704f-2f35-4058-b733-e1c72673463b",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1596437424",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "text/html;charset=UTF-8")
        ),
        Step(
            RunRequest("/login/password")
            .get("/login/password")
            .with_headers(
                **{
                    "Host": "${host}",
                    "Connection": "keep-alive",
                    "Upgrade-Insecure-Requests": "1",
                    "User-Agent": "HttpRunner/${get_httprunner_version()}",
                    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "Sec-Fetch-Site": "same-origin",
                    "Sec-Fetch-Mode": "navigate",
                    "Sec-Fetch-User": "?1",
                    "Sec-Fetch-Dest": "document",
                    "Referer": "https://${host}/login",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,zh-TW;q=0.8,en-US;q=0.7,en;q=0.6",
                    "Cookie": "data_unique_id=7222cae2-b7dc-4408-9f71-807c68a3eb81; language=en-US; country=US; reg_entrance=https%3A%2F%2F${host}%2F; Hm_lvt_4426cbb0486a79ea049b4ad52d81b504=1596433171; _ga=GA1.2.1822844197.1596433171; _gid=GA1.2.2112073243.1596433171; s_v_web_id=kde36rau_LbJCnUtY_WxfM_48aF_Bea9_0F8PeXcfQ9MB; mubu_inner=1; csrf_token=a7d74323-93cd-42c0-925b-db9e8156ff96; SESSION=d94cb122-9971-41b6-94c0-73367f7828d1; data-unique-id=9221b340-d555-11ea-8191-09cb402f42fc; _gat=1; SLARDAR_WEB_ID=3d82ea0c-3404-44be-bd0b-752987acd010; Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504=1596437431; reg_prepareId=173b3160664-173b3160418-405b-b009-127f9ee6f272; reg_focusId=e1ac6342-8037-405b-b009-173b3161767",
                }
            )
            .with_cookies(
                **{
                    "data_unique_id": "7222cae2-b7dc-4408-9f71-807c68a3eb81",
                    "language": "en-US",
                    "country": "US",
                    "reg_entrance": "https%3A%2F%2F${host}%2F",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1596433171",
                    "_ga": "GA1.2.1822844197.1596433171",
                    "_gid": "GA1.2.2112073243.1596433171",
                    "s_v_web_id": "kde36rau_LbJCnUtY_WxfM_48aF_Bea9_0F8PeXcfQ9MB",
                    "mubu_inner": "1",
                    "csrf_token": "a7d74323-93cd-42c0-925b-db9e8156ff96",
                    "SESSION": "d94cb122-9971-41b6-94c0-73367f7828d1",
                    "data-unique-id": "9221b340-d555-11ea-8191-09cb402f42fc",
                    "_gat": "1",
                    "SLARDAR_WEB_ID": "3d82ea0c-3404-44be-bd0b-752987acd010",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1596437431",
                    "reg_prepareId": "173b3160664-173b3160418-405b-b009-127f9ee6f272",
                    "reg_focusId": "e1ac6342-8037-405b-b009-173b3161767",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "text/html;charset=UTF-8")
        ),
        Step(
            RunRequest("/api/login/submit")
            .post("/api/login/submit")
            .with_headers(
                **{
                    "Host": "${host}",
                    "Connection": "keep-alive",
                    "Content-Length": "33",
                    "Accept": "application/json, text/javascript, */*; q=0.01",
                    "X-Requested-With": "XMLHttpRequest",
                    "User-Agent": "HttpRunner/${get_httprunner_version()}",
                    "Content-Type": "application/x-www-form-urlencoded; charset=UTF-8",
                    "Origin": "https://${host}",
                    "Sec-Fetch-Site": "same-origin",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Dest": "empty",
                    "Referer": "https://${host}/login/password",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,zh-TW;q=0.8,en-US;q=0.7,en;q=0.6",
                    "Cookie": "data_unique_id=7222cae2-b7dc-4408-9f71-807c68a3eb81; language=en-US; country=US; reg_entrance=https%3A%2F%2F${host}%2F; Hm_lvt_4426cbb0486a79ea049b4ad52d81b504=1596433171; _ga=GA1.2.1822844197.1596433171; _gid=GA1.2.2112073243.1596433171; s_v_web_id=kde36rau_LbJCnUtY_WxfM_48aF_Bea9_0F8PeXcfQ9MB; mubu_inner=1; csrf_token=a7d74323-93cd-42c0-925b-db9e8156ff96; SESSION=d94cb122-9971-41b6-94c0-73367f7828d1; data-unique-id=9221b340-d555-11ea-8191-09cb402f42fc; _gat=1; reg_prepareId=173b3160664-173b3160418-405b-b009-127f9ee6f272; reg_focusId=e1ac6342-8037-405b-b009-173b3161767; SLARDAR_WEB_ID=4e78a5be-7edd-463c-a245-33631262de37; Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504=1596437437",
                }
            )
            .with_cookies(
                **{
                    "data_unique_id": "7222cae2-b7dc-4408-9f71-807c68a3eb81",
                    "language": "en-US",
                    "country": "US",
                    "reg_entrance": "https%3A%2F%2F${host}%2F",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1596433171",
                    "_ga": "GA1.2.1822844197.1596433171",
                    "_gid": "GA1.2.2112073243.1596433171",
                    "s_v_web_id": "kde36rau_LbJCnUtY_WxfM_48aF_Bea9_0F8PeXcfQ9MB",
                    "mubu_inner": "1",
                    "csrf_token": "a7d74323-93cd-42c0-925b-db9e8156ff96",
                    "SESSION": "d94cb122-9971-41b6-94c0-73367f7828d1",
                    "data-unique-id": "9221b340-d555-11ea-8191-09cb402f42fc",
                    "_gat": "1",
                    "reg_prepareId": "173b3160664-173b3160418-405b-b009-127f9ee6f272",
                    "reg_focusId": "e1ac6342-8037-405b-b009-173b3161767",
                    "SLARDAR_WEB_ID": "4e78a5be-7edd-463c-a245-33631262de37",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1596437437",
                }
            )
            .with_data({"phone": "${phone}", "password": "${password}"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", None)
            .assert_equal("body.data.next","/list")
        ),
        Step(
            RunRequest("/list")
            .get("/list")
            .with_headers(
                **{
                    "Host": "${host}",
                    "Connection": "keep-alive",
                    "Upgrade-Insecure-Requests": "1",
                    "User-Agent": "HttpRunner/${get_httprunner_version()}",
                    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "Sec-Fetch-Site": "same-origin",
                    "Sec-Fetch-Mode": "navigate",
                    "Sec-Fetch-User": "?1",
                    "Sec-Fetch-Dest": "document",
                    "Referer": "https://${host}/login/password",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,zh-TW;q=0.8,en-US;q=0.7,en;q=0.6",
                    "Cookie": "data_unique_id=7222cae2-b7dc-4408-9f71-807c68a3eb81; language=en-US; country=US; reg_entrance=https%3A%2F%2F${host}%2F; Hm_lvt_4426cbb0486a79ea049b4ad52d81b504=1596433171; _ga=GA1.2.1822844197.1596433171; _gid=GA1.2.2112073243.1596433171; s_v_web_id=kde36rau_LbJCnUtY_WxfM_48aF_Bea9_0F8PeXcfQ9MB; mubu_inner=1; csrf_token=a7d74323-93cd-42c0-925b-db9e8156ff96; SESSION=d94cb122-9971-41b6-94c0-73367f7828d1; data-unique-id=9221b340-d555-11ea-8191-09cb402f42fc; _gat=1; reg_prepareId=173b3160664-173b3160418-405b-b009-127f9ee6f272; reg_focusId=e1ac6342-8037-405b-b009-173b3161767; SLARDAR_WEB_ID=4e78a5be-7edd-463c-a245-33631262de37; Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504=1596437437; Jwt-Token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiODQ5MTE4MiIsImV4cCI6MTU5OTAyOTQ0NSwiaWF0IjoxNTk2NDM3NDQ1fQ.MNuIiNww73fm28w6ELIvXl0CccwDVLMAjur9gs0zzsmsoJF9GHPTZ4oQ6tlsf4nTjyXXdATenU9mpSq8vZ9qow",
                }
            )
            .with_cookies(
                **{
                    "data_unique_id": "7222cae2-b7dc-4408-9f71-807c68a3eb81",
                    "language": "en-US",
                    "country": "US",
                    "reg_entrance": "https%3A%2F%2F${host}%2F",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1596433171",
                    "_ga": "GA1.2.1822844197.1596433171",
                    "_gid": "GA1.2.2112073243.1596433171",
                    "s_v_web_id": "kde36rau_LbJCnUtY_WxfM_48aF_Bea9_0F8PeXcfQ9MB",
                    "mubu_inner": "1",
                    "csrf_token": "a7d74323-93cd-42c0-925b-db9e8156ff96",
                    "SESSION": "d94cb122-9971-41b6-94c0-73367f7828d1",
                    "data-unique-id": "9221b340-d555-11ea-8191-09cb402f42fc",
                    "_gat": "1",
                    "reg_prepareId": "173b3160664-173b3160418-405b-b009-127f9ee6f272",
                    "reg_focusId": "e1ac6342-8037-405b-b009-173b3161767",
                    "SLARDAR_WEB_ID": "4e78a5be-7edd-463c-a245-33631262de37",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1596437437",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiODQ5MTE4MiIsImV4cCI6MTU5OTAyOTQ0NSwiaWF0IjoxNTk2NDM3NDQ1fQ.MNuIiNww73fm28w6ELIvXl0CccwDVLMAjur9gs0zzsmsoJF9GHPTZ4oQ6tlsf4nTjyXXdATenU9mpSq8vZ9qow",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "text/html;charset=UTF-8")
        ),
        Step(
            RunRequest("/api/list/tip_new_update")
            .post("/api/list/tip_new_update")
            .with_headers(
                **{
                    "Host": "${host}",
                    "Connection": "keep-alive",
                    "Content-Length": "0",
                    "Accept": "application/json, text/javascript, */*; q=0.01",
                    "User-Agent": "HttpRunner/${get_httprunner_version()}",
                    "X-Requested-With": "XMLHttpRequest",
                    "Origin": "https://${host}",
                    "Sec-Fetch-Site": "same-origin",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Dest": "empty",
                    "Referer": "https://${host}/list",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,zh-TW;q=0.8,en-US;q=0.7,en;q=0.6",
                    "Cookie": "data_unique_id=7222cae2-b7dc-4408-9f71-807c68a3eb81; language=en-US; country=US; reg_entrance=https%3A%2F%2F${host}%2F; Hm_lvt_4426cbb0486a79ea049b4ad52d81b504=1596433171; _ga=GA1.2.1822844197.1596433171; _gid=GA1.2.2112073243.1596433171; s_v_web_id=kde36rau_LbJCnUtY_WxfM_48aF_Bea9_0F8PeXcfQ9MB; mubu_inner=1; csrf_token=a7d74323-93cd-42c0-925b-db9e8156ff96; SESSION=d94cb122-9971-41b6-94c0-73367f7828d1; data-unique-id=9221b340-d555-11ea-8191-09cb402f42fc; _gat=1; reg_prepareId=173b3160664-173b3160418-405b-b009-127f9ee6f272; reg_focusId=e1ac6342-8037-405b-b009-173b3161767; SLARDAR_WEB_ID=4e78a5be-7edd-463c-a245-33631262de37; Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504=1596437437; Jwt-Token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiODQ5MTE4MiIsImV4cCI6MTU5OTAyOTQ0NSwiaWF0IjoxNTk2NDM3NDQ1fQ.MNuIiNww73fm28w6ELIvXl0CccwDVLMAjur9gs0zzsmsoJF9GHPTZ4oQ6tlsf4nTjyXXdATenU9mpSq8vZ9qow",
                }
            )
            .with_cookies(
                **{
                    "data_unique_id": "7222cae2-b7dc-4408-9f71-807c68a3eb81",
                    "language": "en-US",
                    "country": "US",
                    "reg_entrance": "https%3A%2F%2F${host}%2F",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1596433171",
                    "_ga": "GA1.2.1822844197.1596433171",
                    "_gid": "GA1.2.2112073243.1596433171",
                    "s_v_web_id": "kde36rau_LbJCnUtY_WxfM_48aF_Bea9_0F8PeXcfQ9MB",
                    "mubu_inner": "1",
                    "csrf_token": "a7d74323-93cd-42c0-925b-db9e8156ff96",
                    "SESSION": "d94cb122-9971-41b6-94c0-73367f7828d1",
                    "data-unique-id": "9221b340-d555-11ea-8191-09cb402f42fc",
                    "_gat": "1",
                    "reg_prepareId": "173b3160664-173b3160418-405b-b009-127f9ee6f272",
                    "reg_focusId": "e1ac6342-8037-405b-b009-173b3161767",
                    "SLARDAR_WEB_ID": "4e78a5be-7edd-463c-a245-33631262de37",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1596437437",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiODQ5MTE4MiIsImV4cCI6MTU5OTAyOTQ0NSwiaWF0IjoxNTk2NDM3NDQ1fQ.MNuIiNww73fm28w6ELIvXl0CccwDVLMAjur9gs0zzsmsoJF9GHPTZ4oQ6tlsf4nTjyXXdATenU9mpSq8vZ9qow",
                }
            )
            .with_data("")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", None)
        ),
        Step(
            RunRequest("/api/list/get")
            .post("/api/list/get")
            .with_headers(
                **{
                    "Host": "${host}",
                    "Connection": "keep-alive",
                    "Content-Length": "38",
                    "Accept": "application/json, text/javascript, */*; q=0.01",
                    "X-Requested-With": "XMLHttpRequest",
                    "User-Agent": "HttpRunner/${get_httprunner_version()}",
                    "Content-Type": "application/x-www-form-urlencoded; charset=UTF-8",
                    "Origin": "https://${host}",
                    "Sec-Fetch-Site": "same-origin",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Dest": "empty",
                    "Referer": "https://${host}/list",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,zh-TW;q=0.8,en-US;q=0.7,en;q=0.6",
                    "Cookie": "data_unique_id=7222cae2-b7dc-4408-9f71-807c68a3eb81; language=en-US; country=US; reg_entrance=https%3A%2F%2F${host}%2F; Hm_lvt_4426cbb0486a79ea049b4ad52d81b504=1596433171; _ga=GA1.2.1822844197.1596433171; _gid=GA1.2.2112073243.1596433171; s_v_web_id=kde36rau_LbJCnUtY_WxfM_48aF_Bea9_0F8PeXcfQ9MB; mubu_inner=1; csrf_token=a7d74323-93cd-42c0-925b-db9e8156ff96; SESSION=d94cb122-9971-41b6-94c0-73367f7828d1; data-unique-id=9221b340-d555-11ea-8191-09cb402f42fc; _gat=1; reg_prepareId=173b3160664-173b3160418-405b-b009-127f9ee6f272; reg_focusId=e1ac6342-8037-405b-b009-173b3161767; SLARDAR_WEB_ID=4e78a5be-7edd-463c-a245-33631262de37; Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504=1596437437; Jwt-Token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiODQ5MTE4MiIsImV4cCI6MTU5OTAyOTQ0NSwiaWF0IjoxNTk2NDM3NDQ1fQ.MNuIiNww73fm28w6ELIvXl0CccwDVLMAjur9gs0zzsmsoJF9GHPTZ4oQ6tlsf4nTjyXXdATenU9mpSq8vZ9qow",
                }
            )
            .with_cookies(
                **{
                    "data_unique_id": "7222cae2-b7dc-4408-9f71-807c68a3eb81",
                    "language": "en-US",
                    "country": "US",
                    "reg_entrance": "https%3A%2F%2F${host}%2F",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1596433171",
                    "_ga": "GA1.2.1822844197.1596433171",
                    "_gid": "GA1.2.2112073243.1596433171",
                    "s_v_web_id": "kde36rau_LbJCnUtY_WxfM_48aF_Bea9_0F8PeXcfQ9MB",
                    "mubu_inner": "1",
                    "csrf_token": "a7d74323-93cd-42c0-925b-db9e8156ff96",
                    "SESSION": "d94cb122-9971-41b6-94c0-73367f7828d1",
                    "data-unique-id": "9221b340-d555-11ea-8191-09cb402f42fc",
                    "_gat": "1",
                    "reg_prepareId": "173b3160664-173b3160418-405b-b009-127f9ee6f272",
                    "reg_focusId": "e1ac6342-8037-405b-b009-173b3161767",
                    "SLARDAR_WEB_ID": "4e78a5be-7edd-463c-a245-33631262de37",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1596437437",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiODQ5MTE4MiIsImV4cCI6MTU5OTAyOTQ0NSwiaWF0IjoxNTk2NDM3NDQ1fQ.MNuIiNww73fm28w6ELIvXl0CccwDVLMAjur9gs0zzsmsoJF9GHPTZ4oQ6tlsf4nTjyXXdATenU9mpSq8vZ9qow",
                }
            )
            .with_data({"folderId": "0", "sort": "time", "keywords": "", "source": ""}).extract().with_jmespath('body.data.userId','userId')
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", None)
        ),
        Step(
            RunRequest("/api/message/get_message_unread")
            .post("/api/message/get_message_unread")
            .with_headers(
                **{
                    "Host": "${host}",
                    "Connection": "keep-alive",
                    "Content-Length": "0",
                    "Accept": "application/json, text/javascript, */*; q=0.01",
                    "User-Agent": "HttpRunner/${get_httprunner_version()}",
                    "X-Requested-With": "XMLHttpRequest",
                    "Origin": "https://${host}",
                    "Sec-Fetch-Site": "same-origin",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Dest": "empty",
                    "Referer": "https://${host}/list",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9,zh-TW;q=0.8,en-US;q=0.7,en;q=0.6",
                    "Cookie": "data_unique_id=7222cae2-b7dc-4408-9f71-807c68a3eb81; language=en-US; country=US; reg_entrance=https%3A%2F%2F${host}%2F; Hm_lvt_4426cbb0486a79ea049b4ad52d81b504=1596433171; _ga=GA1.2.1822844197.1596433171; _gid=GA1.2.2112073243.1596433171; s_v_web_id=kde36rau_LbJCnUtY_WxfM_48aF_Bea9_0F8PeXcfQ9MB; mubu_inner=1; csrf_token=a7d74323-93cd-42c0-925b-db9e8156ff96; SESSION=d94cb122-9971-41b6-94c0-73367f7828d1; data-unique-id=9221b340-d555-11ea-8191-09cb402f42fc; _gat=1; reg_prepareId=173b3160664-173b3160418-405b-b009-127f9ee6f272; reg_focusId=e1ac6342-8037-405b-b009-173b3161767; SLARDAR_WEB_ID=4e78a5be-7edd-463c-a245-33631262de37; Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504=1596437437; Jwt-Token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiODQ5MTE4MiIsImV4cCI6MTU5OTAyOTQ0NSwiaWF0IjoxNTk2NDM3NDQ1fQ.MNuIiNww73fm28w6ELIvXl0CccwDVLMAjur9gs0zzsmsoJF9GHPTZ4oQ6tlsf4nTjyXXdATenU9mpSq8vZ9qow",
                }
            )
            .with_cookies(
                **{
                    "data_unique_id": "7222cae2-b7dc-4408-9f71-807c68a3eb81",
                    "language": "en-US",
                    "country": "US",
                    "reg_entrance": "https%3A%2F%2F${host}%2F",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1596433171",
                    "_ga": "GA1.2.1822844197.1596433171",
                    "_gid": "GA1.2.2112073243.1596433171",
                    "s_v_web_id": "kde36rau_LbJCnUtY_WxfM_48aF_Bea9_0F8PeXcfQ9MB",
                    "mubu_inner": "1",
                    "csrf_token": "a7d74323-93cd-42c0-925b-db9e8156ff96",
                    "SESSION": "d94cb122-9971-41b6-94c0-73367f7828d1",
                    "data-unique-id": "9221b340-d555-11ea-8191-09cb402f42fc",
                    "_gat": "1",
                    "reg_prepareId": "173b3160664-173b3160418-405b-b009-127f9ee6f272",
                    "reg_focusId": "e1ac6342-8037-405b-b009-173b3161767",
                    "SLARDAR_WEB_ID": "4e78a5be-7edd-463c-a245-33631262de37",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1596437437",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiODQ5MTE4MiIsImV4cCI6MTU5OTAyOTQ0NSwiaWF0IjoxNTk2NDM3NDQ1fQ.MNuIiNww73fm28w6ELIvXl0CccwDVLMAjur9gs0zzsmsoJF9GHPTZ4oQ6tlsf4nTjyXXdATenU9mpSq8vZ9qow",
                }
            )
            .with_data("")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", None)
        ),
    ]


if __name__ == "__main__":
    TestCaseLogin().test_start()
